### ISSUE TITLE
cargo deb --install results in I/O error

### ISSUE THREAD

**Issue by injectx** [IamTheCarl/system-mqtt#7] opened 2023-02-09 22:41 UTC
Hi! So I've made sure all dependencies are installed but when I run `cargo deb --install` I get 

> cargo-
> deb: I/O error: No such file or directory (os error 2)
>   because: No such file or directory (os error 2)
> 

at the end. 

Any thoughts on this? Been trying to get my Intel NUC's stats into Home Assistant for ages now.

**Comment by IamTheCarl** [comment] 2023-02-11 23:06
Hmm, that's pretty vague.
Can you try running `cargo deb --verbose`? That might tell us what it's failing to find.

Also, could you try just running `cargo build --release`? That'll let us know that the issue is in cargo-deb and not in the build process itself.

**Comment by injectx** [comment] 2023-02-11 23:25
Thanks for your reply, appreciated.

> 

`cargo deb --verbose`

> Fresh system-mqtt v0.2.1 (/home/gits/system-mqtt)
>     Finished release [optimized] target(s) in 0.11s
> info: Stripped '/home/gits/system-mqtt/target/release/system-mqtt'
> info: - -> usr/share/doc/system-mqtt/copyright (187B)
> info: README.md -> usr/share/doc/system-mqtt/README.md (6KB)
> info: /home/gits/system-mqtt/systemd/system-mqtt.service -> lib/systemd/system/system-mqtt.service (257B)
> info: /home/gits/system-mqtt/target/debian/system-mqtt.tmp0-stripped -> usr/bin/system-mqtt (4MB)
> info: compressed/original ratio 1255328/3973120 (31%)
> /home/gits/system-mqtt/target/debian/system-mqtt_0.2.1_amd64.deb

`cargo build --release`

> Finished release [optimized] target(s) in 0.10s

Can't see it return any errors.

**Comment by IamTheCarl** [comment] 2023-02-12 00:16
Sounds like only the install step failed then.
My guess is that apt-get is failing.

Try running `sudo apt-get install --reinstall /home/gits/system-mqtt/target/debian/system-mqtt_0.2.1_amd64.deb` and see how far that gets.

**Comment by injectx** [comment] 2023-02-12 13:38
That seems to work, which is nice.
Though I'm receiving a different erorr message when I try to run `system-mqtt set-password`:

> Fatal error: Keyring Error: Secret Service Error: Dbus error: "Unable to autolaunch a dbus-daemon without a $DISPLAY for X11"
> If you have not yet set the password run `system-mqtt set-password`.

**Comment by IamTheCarl** [comment] 2023-02-13 16:51
Hmm, that may be related to this issue: https://github.com/IamTheCarl/system-mqtt/issues/2

I didn't want to just dumbly store the password in a plain text file so it depends on dbus.
I'm thinking that with how often this seems to be an issue I should permit an alternative where it can be stored in a plain text file but with read permissions revoked for everyone but root.

**Comment by injectx** [comment] 2023-02-14 08:57
I get it, thanks for taking the time to look into it. I'll guess I have to wait a little longer.

**Comment by IamTheCarl** [comment] 2023-02-16 18:12
You're welcome.
Since your issue looks to be #2 at this point, I'm going to close this issue.

**Closed as completed by IamTheCarl** 2023-02-16 18:12 UTC
